version: "3"
services:
  mbtileserver:
    image: headway_tileserver
    build: ./tileserver/image
    environment:
      PORT: 8000
    env_file: .env
    volumes:
      - "./data/:/data/:ro"
  photon:
    image: headway_photon
    build: ./geocoder/photon
    env_file: .env
    volumes:
      - "./data/:/data/:ro"
  nominatim:
    image: headway_nominatim
    build: ./geocoder/nominatim
    environment:
      PBF_PATH: /data/${HEADWAY_AREA}.osm.pbf
      HEADWAY_NOMINATIM_FILE: /data/${HEADWAY_AREA}.nominatim.sql
      HEADWAY_NOMINATIM_TOKENIZER: /data/${HEADWAY_AREA}.nominatim_tokenizer.tgz
    env_file: .env
    volumes:
      - "./data/:/data/:ro"
  otp:
    image: headway_otp
    build: ./otp/run
    env_file: .env
    volumes:
      - "./data/:/data/:ro"
  valhalla:
    image: headway_valhalla
    build: ./valhalla/run
    env_file: .env
    volumes:
      - "./data/:/data_mount/:ro"
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
  nginx:
    image: headway_nginx
    build: ./web
    env_file: .env
    environment:
      HEADWAY_RESOLVER: 127.0.0.11
      HEADWAY_GRAPHHOPPER_URL: http://graphhopper:8989
      HEADWAY_NOMINATIM_URL: http://nominatim:8080
      HEADWAY_PHOTON_URL: http://photon:2322
      HEADWAY_TILESERVER_URL: http://mbtileserver:8000
    ports:
      - "8080:8080"
    volumes:
      - "./data/:/data/:ro"
    depends_on:
      - "valhalla"
      - "otp"
      - "nominatim"
      - "photon"
      - "mbtileserver"
