apiVersion: v1
kind: Service
metadata:
  name: headway
spec:
  type: NodePort
  selector:
    app: headway
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8080