apiVersion: apps/v1
kind: Deployment
metadata:
  name: headway-tileserver-deployment
spec:
  selector:
    matchLabels:
      app: tileserver
  replicas: 1
  template:
    metadata:
      labels:
        app: tileserver
    spec:
      initContainers:
        - name: tileserver-init
          image: ghcr.io/headwaymaps/tileserver-init:dev
          imagePullPolicy: Always
          volumeMounts:
            - name: tileserver-volume
              mountPath: /data
          env:
            - name: FONT_ARTIFACT_DEST_PATH
              value: /data/fonts/fonts.tar
            - name: SPRITE_ARTIFACT_DEST_PATH
              value: /data/sprite/static/sprite.tar
            - name: MBTILES_ARTIFACT_DEST_PATH
              value: /data/data.mbtiles
            - name: FONT_ARTIFACT_URL
              valueFrom:
                configMapKeyRef:
                  name: deployment-config
                  key: font-source-url
            - name: SPRITE_ARTIFACT_URL
              valueFrom:
                configMapKeyRef:
                  name: deployment-config
                  key: sprite-source-url
            - name: MBTILES_ARTIFACT_URL
              valueFrom:
                configMapKeyRef:
                  name: deployment-config
                  key: mbtiles-source-url
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 100Mi
      containers:
        - name: tileserver
          image: ghcr.io/headwaymaps/tileserver:dev
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: tileserver-volume
              mountPath: /data
          env:
            - name: HEADWAY_AREA
              value: data
            - name: PORT
              value: "8000"
          resources:
            limits:
              memory: 500Mi
            requests:
              memory: 200Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 10
      volumes:
        - name: tileserver-volume
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 200Gi
