name: Push

on:
  push:
    branches: [main]

jobs:
  build:
    name: Push images to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - uses: actions/checkout@v2
      - name: Earthly version check
        run: earthly --version
      - name: Push images
        run: docker login --username "${{ secrets.DOCKERHUB_USERNAME_PUSH }}" --password "${{ secrets.DOCKERHUB_PASSWORD_PUSH }}" && earthly --push +images
